### ISSUE TITLE
csrf token was not found error on create action

### ISSUE THREAD

**Issue by igormisha** [jakub-zawislak/formex#24]
My controller looks like this:

```
defmodule HelloWeb.ResumeFormexController do
  use HelloWeb, :controller
  alias Hello.Hr.{Resume, ResumeType}

  def index(conn, _params) do
    resumes = Hr.list_resumes()
    render(conn, "index.html", resumes: resumes)
  end

  def new(conn, params) do
    form = create_form(ResumeType, %Resume{})

    render(conn, "new.html", form: form)
  end

  def create(conn, params) do
    ResumeType
    |> create_form(%Resume{}, params)
    |> handle_form
    |> case do
      {:ok, resume} ->
        redirect(conn, to: Routes.resume_path(conn, :show, resume))
      {:error, form} ->
        render(conn, "new.html", form: form)
    end
  end

  def show(conn, %{"id" => id}) do
    resume = Hr.get_resume!(id)
    inspect(resume)
    render(conn, "show.html", resume: resume)
  end
end
```
When I submit form I get:

```
iex(2)> [info] POST /resumes-formex
iex(2)> [debug] Processing with HelloWeb.ResumeFormexController.create/2
  Parameters: %{"_csrf_token" => "OgN4fAQFGwBJMG5xOxQpS38aIyFSJgAAmk7M0HNOqtA2Pdaz7Nvp3A==", "_utf8" => "тЬУ", "resume" => %{"birthday"
=> %{"day" => "2", "month" => "3", "year" => "2014"}, "data" => %{"experiences" => %{"0" => %{"city" => "Kiev", "end_date" => %{"day" => "20", "month" => "12", "year" => "2016"}, "formex_id" => "652e666a-6d9e-450c-bf5d-ee9f0d6e6b66", "position" => "Chef welder", "start_date" => %{"day" => "1", "month" => "8", "year" => "2014"}}, "1" => %{"city" => "Lvov", "end_date" => %{"day" => "1", "month" => "1", "year" => "2019"}, "formex_id" => "e89497aa-2f65-4aa5-b42e-4417569aeed7", "position" => "Master", "start_date" => %{"day" => "20", "month" => "12", "year" => "2016"}}}, "id" => "", "welder" => %{"horizontal" => "true", "id" => "", "vertical" => "false"}}, "full_name" => "John Doe", "joined_at" => %{"day" => "4", "hour" => "3", "minute" => "10", "month" => "6", "year" => "2016"}, "next_event" => %{"day" => "6", "hour" => "11", "minute" => "0", "month" => "10", "year" => "2019"}, "start_work_time" => %{"hour" => "7", "minute" => "30"}}}
  Pipelines: [:browser]
iex(2)> [info] Sent 500 in 47ms
iex(2)> [error] #PID<0.1056.0> running HelloWeb.Endpoint (connection #PID<0.1055.0>, stream id 1) terminated
Server: localhost:4000 (http)
Request: POST /resumes-formex
** (exit) an exception was raised:
    ** (KeyError) key :_csrf_token not found in: %Hello.Hr.Resume{__meta__: #Ecto.Schema.Metadata<:built, "resumes">, birthday: nil, data: nil, full_name: nil, id: nil, inserted_at: nil, joined_at: nil, next_event: nil, start_work_time: nil, updated_at: nil}
        (stdlib) :maps.get(:_csrf_token, %Hello.Hr.Resume{__meta__: #Ecto.Schema.Metadata<:built, "resumes">, birthday: nil, data: nil,
full_name: nil, id: nil, inserted_at: nil, joined_at: nil, next_event: nil, start_work_time: nil, updated_at: nil})
        (elixir) lib/map.ex:267: Map.update!/3
        (stdlib) maps.erl:257: :maps.fold_1/3
        (formex) lib/formex/builder.ex:146: Formex.Builder.apply_params/1
        (formex) lib/formex/builder.ex:52: Formex.Builder.create_form/5
        (hello) lib/hello_web/controllers/resume_formex_controller.ex:18: HelloWeb.ResumeFormexController.create/2
        (hello) lib/hello_web/controllers/resume_formex_controller.ex:1: HelloWeb.ResumeFormexController.action/2
        (hello) lib/hello_web/controllers/resume_formex_controller.ex:1: HelloWeb.ResumeFormexController.phoenix_controller_pipeline/2
        (hello) lib/hello_web/endpoint.ex:1: HelloWeb.Endpoint.instrument/4
        (phoenix) lib/phoenix/router.ex:275: Phoenix.Router.__call__/1
        (hello) lib/hello_web/endpoint.ex:1: HelloWeb.Endpoint.plug_builder_call/2
        (hello) lib/plug/debugger.ex:122: HelloWeb.Endpoint."call (overridable 3)"/2
        (hello) lib/hello_web/endpoint.ex:1: HelloWeb.Endpoint.call/2
        (phoenix) lib/phoenix/endpoint/cowboy2_handler.ex:34: Phoenix.Endpoint.Cowboy2Handler.init/2
        (cowboy) d:/test/hello/deps/cowboy/src/cowboy_handler.erl:41: :cowboy_handler.execute/2
        (cowboy) d:/test/hello/deps/cowboy/src/cowboy_stream_h.erl:296: :cowboy_stream_h.execute/3
        (cowboy) d:/test/hello/deps/cowboy/src/cowboy_stream_h.erl:274: :cowboy_stream_h.request_process/3
        (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

**Comment by igormisha** [comment]
Solved it, the create function should look like this:
```
  def create(conn, %{"resume" => resume_params}) do
    ResumeType
    |> create_form(%Resume{}, resume_params)
    |> handle_form
    |> case do
      {:ok, resume} ->
        resume = Hello.Repo.insert!(resume)
        redirect(conn, to: Routes.resume_path(conn, :show, resume))
      {:error, form} ->
        render(conn, "new.html", form: form)
    end
  end
```
